all:
  children:
    masters:
      hosts:
        k8s-master-01:
          ansible_host: <MASTER_01_IP>

    workers:
      hosts:
        k8s-worker-01:
          ansible_host: <WORKER_01_IP>
        k8s-worker-02:
          ansible_host: <WORKER_02_IP>
